<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>plhtml</string>
		<string>tpl</string>
	</array>
	<key>name</key>
	<string>Perl (Tenjin Template)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;\?pl)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.begin.pltenjin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.end.pltenjin</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.perl.pltenjin.block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[==?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.begin.pltenjin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(==?\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.end.pltenjin</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.perl.pltenjin.expression</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.pltenjin</string>
	<key>uuid</key>
	<string>E17511DC-03D7-4782-B03E-010F639126A7</string>
</dict>
</plist>
